spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
              client-id: 449398939130673
              client-secret: 8146a350888e2f121e251ca262834fbd
          google:
              client-id: 494606077602-ngb5fq9idpvp43272sqc1n0qdfvrb1h8.apps.googleusercontent.com
              client-secret: 09QIywfKoI4i-Sr-2BkI1k1p
custom:
  oauth2:
    kakao:
      client-id: 406bf84ab6137543f727b172798ad11d